-- Slice 7：员工主档（个人主档）生效日期版本化
-- 目标：支持 GET /employees/{id}?asOfDate= 快照查看；支持 NEW_VERSION 创建未来/历史版本并自动衔接时间轴

CREATE TABLE IF NOT EXISTS employee_master_version (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  employee_id BIGINT NOT NULL,
  effective_start_date DATE NOT NULL,
  effective_end_date DATE NULL,

  full_name VARCHAR(128) NOT NULL,
  ad_account VARCHAR(128) NULL,
  gender VARCHAR(16) NULL,
  mobile VARCHAR(512) NOT NULL COMMENT 'AES 加密存储（与 employee.mobile 同口径）',
  company_email VARCHAR(128) NULL,
  personal_email VARCHAR(128) NULL,

  marital_status VARCHAR(64) NULL,
  political_affiliation VARCHAR(64) NULL,
  highest_education VARCHAR(64) NULL,
  highest_education_grad_date DATE NULL,
  fertility_status VARCHAR(64) NULL,
  ethnicity VARCHAR(64) NULL,
  hobbies VARCHAR(255) NULL,
  nationality VARCHAR(64) NULL,
  household_type VARCHAR(64) NULL,
  household_location VARCHAR(255) NULL,
  party_org_transferred TINYINT(1) NULL,
  work_start_date DATE NULL,
  wechat VARCHAR(128) NULL,
  office_phone VARCHAR(64) NULL,
  office_extension VARCHAR(32) NULL,
  home_phone VARCHAR(64) NULL,
  id_card_address VARCHAR(255) NULL,
  residence_address VARCHAR(255) NULL,
  emergency_contact_name VARCHAR(128) NULL,
  emergency_contact_phone VARCHAR(64) NULL,
  emergency_contact_relation VARCHAR(64) NULL,
  recruitment_channel VARCHAR(64) NULL,
  recruitment_channel_detail VARCHAR(255) NULL,
  group_seniority_start_date DATE NULL,

  hire_date DATE NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',

  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT NULL,
  updated_by BIGINT NULL,

  UNIQUE KEY uk_employee_master_version (employee_id, effective_start_date),
  KEY idx_emv_employee_range (employee_id, effective_end_date, effective_start_date),
  CONSTRAINT fk_emv_employee_id FOREIGN KEY (employee_id) REFERENCES employee(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 初始化：为现有 employee 写入首条版本（以 hire_date 作为生效开始日）
INSERT INTO employee_master_version (
  employee_id,
  effective_start_date,
  effective_end_date,
  full_name,
  ad_account,
  gender,
  mobile,
  company_email,
  personal_email,
  marital_status,
  political_affiliation,
  highest_education,
  highest_education_grad_date,
  fertility_status,
  ethnicity,
  hobbies,
  nationality,
  household_type,
  household_location,
  party_org_transferred,
  work_start_date,
  wechat,
  office_phone,
  office_extension,
  home_phone,
  id_card_address,
  residence_address,
  emergency_contact_name,
  emergency_contact_phone,
  emergency_contact_relation,
  recruitment_channel,
  recruitment_channel_detail,
  group_seniority_start_date,
  hire_date,
  status,
  created_at,
  updated_at,
  created_by,
  updated_by
)
SELECT
  e.id,
  e.hire_date,
  NULL,
  e.full_name,
  e.ad_account,
  e.gender,
  e.mobile,
  e.company_email,
  e.personal_email,
  e.marital_status,
  e.political_affiliation,
  e.highest_education,
  e.highest_education_grad_date,
  e.fertility_status,
  e.ethnicity,
  e.hobbies,
  e.nationality,
  e.household_type,
  e.household_location,
  e.party_org_transferred,
  e.work_start_date,
  e.wechat,
  e.office_phone,
  e.office_extension,
  e.home_phone,
  e.id_card_address,
  e.residence_address,
  e.emergency_contact_name,
  e.emergency_contact_phone,
  e.emergency_contact_relation,
  e.recruitment_channel,
  e.recruitment_channel_detail,
  e.group_seniority_start_date,
  e.hire_date,
  e.status,
  e.created_at,
  e.updated_at,
  e.created_by,
  e.updated_by
FROM employee e
WHERE NOT EXISTS (
  SELECT 1
  FROM employee_master_version v
  WHERE v.employee_id = e.id
);

