import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  Award,
  BadgeCheck,
  BarChart3,
  BookOpen,
  Bot,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  ClipboardList,
  Cog,
  CreditCard,
  Database,
  FileText,
  FolderKanban,
  Gift,
  GraduationCap,
  HeartPulse,
  Home,
  IdCard,
  Landmark,
  LayoutDashboard,
  LayoutGrid,
  LifeBuoy,
  LineChart,
  Network,
  Paperclip,
  PieChart,
  ScrollText,
  Settings2,
  Shield,
  ShieldCheck,
  Sparkles,
  Trophy,
  UserRound,
  Users,
  Workflow,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  LayoutDashboard,
  Building2,
  Network,
  BriefcaseBusiness,
  Settings2,
  ClipboardList,
  ShieldCheck,
  LifeBuoy,
  Shield,
  Workflow,
  BarChart3,
  Cog,
  Database,
  IdCard,
  Users,
  UserRound,
  PieChart,
  FileText,
  ScrollText,
  CreditCard,
  Landmark,
  Gift,
  HeartPulse,
  Building,
  Home,
  Paperclip,
  GraduationCap,
  Briefcase,
  Award,
  BadgeCheck,
  Trophy,
  AlertTriangle,
  BookOpen,
  LineChart,
  Sparkles,
  LayoutGrid,
  FolderKanban,
  Bot,
};

export function resolveMenuIcon(name?: string | null): LucideIcon {
  if (!name) return ClipboardList;
  return ICON_MAP[name] ?? ClipboardList;
}
